### ISSUE TITLE
How to get the G.txt file from the scratch?

### ISSUE THREAD

**Issue by lybird300** [biostatLu/IEHC#1]
Hi there,

Thank you for this tool. I'm interesting in testing the survival associations of some matrixEqtl results using your tool, but having trouble figuring out what to import as the G.txt file (the weighted burden test score as mentioned in the "Example.md" page).  Are these values the beta values produced by matrixEqtl? If not, could you please teach me how to calculate them? Sorry I'm new to this field. 

Thanks again, 
Sincerely,

**Comment by biostatLu** [comment]
Dear lybird300,

Thank you for your interest in our method. We used Genotypes multiplied by eQTL effect sizes obtained from GTEx to calculate the weighted burden test score (G.txt file). I hope it will be helpful for you. Please do not hesitate to contact us if you have any questions regarding IEHC method.

Best wishes,
biostatLu

**Comment by lybird300** [comment]
Got it! Thank you soooooooo much for the prompt reply. Have a nice holiday!
