### ISSUE TITLE
Values in the covariate file (X.txt)

### ISSUE THREAD

**Issue by lybird300** [biostatLu/IEHC#2]
Dear biostatLu,

I noticed the example covariate file (X.txt) contains not the original age, sex, stage but some sort of transformed values. I supplied the IEHC function with regular values (e.g., 43, 1, 1) and it works fine. So I wonder whether the transformation is required. If so, how should I do it? Thank you in advance!

Best,

**Comment by biostatLu** [comment]
Dear lybird300,

Thank you for your interest in our method. The example covariate file (X.txt) is standardized to have mean zero and variance one. I hope it will be helpful for you. Please do not hesitate to contact us if you have any questions regarding IEHC method.

Best wishes,
biostatLu

**Comment by lybird300** [comment]
I see. Thanks for the clarification. One quick follow-up. Do I need to normalize my covariates as such before running the IEHC function?

**Comment by biostatLu** [comment]
In my opinion, the influence of dimensionality can be eliminated by normalizing the covariates, which will not affect the significance of the covariates in Cox model, but will affect the effect size of the covariates in Cox model. I suggest you can normalize the covariates before running the IEHC function.

**Comment by lybird300** [comment]
Will do. Thank you very much!
